apiVersion: v1
kind: ConfigMap
metadata:
  name: portal-monitor-config-test
  namespace: portal-monitor
data:
  domains.txt: |
    # portal.boruxa.com
    # target domain
    tmfxhub.com
    tmmktcn.com
    cnfxplus.com
    cnfinmarket.com
    tmfxpath.com
    tm-fxtrend.com
    cngldfx.com
    tmgldhub.com
    tm-fxgldcn.com
    tminvgld.com
    texunaro.com
    toviqera.com
    tyravexo.com
    qenid.com
    cymivo.com
    jexalo.com
    zobiva.com
    wureli.com
    tm-nexgld.com
    tm-fxharmony.com
    cnfxinv.com
    tmxgm.com
    tmgmktbase.com
    tmfxlumen.com
    tmgldluck.com
    fxcngold.com
    taxunori.com
    tuxoria.com
    fxmaxgld.com
    inv-fxgld.com
    tavorexu.com
    tuqaviro.com
    taxovire.com
    tevunaro.com
    tyvenaro.com
    tuxavero.com
    tovarixu.com
    teqaviro.com
    turavexo.com
    toriqexa.com
    rerixa.com
    boruxa.com
    tmproinv.com
    cninvpro.com
    tmtraderfx.com
    tmnowfx.com
    gldhubzh.com
    fxinvcn.com
    fxcngo.com
    tmzhx.com
    tmgm-insights.com
    tmfxview.com
    austmgm-accounts.com
    choosetmgm.com
    tmgmapac.com
    tm-fxzh.com
    tdmaxtrading.com
    fxtmg.com
    registmgm.com
    tmgm-mkt.com
    tmgxpro.com
    tmg-market.com
    tmg-gl.com
    tmgmgroup.com
    protmg.com
    tmg-fm.com
    tmgmplus.com
    tmg-inv.com
    tmg-plus.com
    tmgmyun.com
    tmgmex.com
    tmgmfun.com
    max-tmgm.com
    tmgcnhub.com
    tm-chinacn.com
    tm-fxcn.com
    protrading-tmgm.com
    tmgmmarkets.com
    tmgmgo.com
    tmg-fx.com
    tmgmsh.com
    trademaxcn.com
    fin-tmg.com
    tmg-fin.com
     tmfxdata.com 

    # jumper Domain
    tmgrowinv.com
    gldfocusmkt.com
    cnfxhero.com
    tminvgain.com
    qaplex.com
    qerian.com
    pilivo.com
    tmgmarkets.com
    trdmaxglobal.com
    trdgmarkets.com
    trdmaxmarkets.com
    tmaxglobalmarkets.com
    tmaxmarkets.com
    tmglobalmarkets.com
    tcyberix.com
    tanelity.com
    fx-tmg.com 
    tmgmdrive.com
    tmgmstrategy.com
    tmgmlink.com
    tmgmconnect.com
    tmgmadvisor.com
    tmgminvest.com
    tmgmportfolio.com
    tmgmreliance.com
    tjer-uysr.com
    tmgmwealth.com
    tmgmexpander.com
    tmgmroadmaps.com
    tmgmteamwork.com
    tmgmjumper.com
    tmg-trd.com
    tmgmtrd.com
    tmgmhub.com

    # ib Domain
    tarenzio.com
    tovrinal.com
    tasmirex.com
    tyrnoxa.com
    texrilo.com
    tovqeni.com
    tevrino.com
    tokryza.com
    tavqrix.com
    tuvqiro.com
    tenqixa.com
    toxqira.com
    tyvnora.com
    tavxiro.com
    tuxvora.com
    tynqiro.com
    tazvora.com
    tevrqix.com
    tiqvona.com
    tovzira.com
    tyrqova.com
    taxvori.com
    teqviro.com