name: CD - Deploy Portal Monitor

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: "Docker image tag"
        required: true
        default: "v1.0.0"

env:
  KUBE_LATEST_VERSION: "v1.36.0"
  HELM_VERSION: "v4.1.3"
  IMAGE_NAME: "jevinwanglb/portal-monitor"

jobs:
  deploy:
    name: Deploy to EKS
    runs-on: arc-runner-set-portal

    steps:
      - name: Test runner
        run: |
          echo "runner ok"
          uname -a

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: ${{ env.KUBE_LATEST_VERSION }}

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: ${{ env.HELM_VERSION }}

      - name: Check Kubernetes access
        run: |
          kubectl auth whoami
          kubectl get namespace portal-monitor

      - name: Show deployment image
        run: |
          echo "Deploy image:"
          echo "${IMAGE_NAME}:${{ inputs.image_tag }}"

      - name: Update Job image
        run: |
          sed \
            -e "s#image: .*#image: ${IMAGE_NAME}:${{ inputs.image_tag }}#" \
            k8s/job.yaml > /tmp/job.yaml

      - name: Deploy ConfigMap
        run: |
          kubectl apply \
            -n portal-monitor \
            -f k8s/configmap.yaml

      - name: Deploy test Job
        run: |
          kubectl delete job portal-monitor-test \
            -n portal-monitor \
            --ignore-not-found

          kubectl apply \
            -n portal-monitor \
            -f /tmp/job.yaml

      - name: Wait for Job
        run: |
          kubectl wait \
            --namespace portal-monitor \
            --for=condition=complete \
            --timeout=10m \
            job/portal-monitor-test

      - name: Show logs
        run: |
          kubectl logs \
            --namespace portal-monitor \
            job/portal-monitor-test